services:
  localstack:
    container_name: url_shortener_localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Edge Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=dynamodb,sqs,s3,lambda,apigateway
      - AWS_DEFAULT_REGION=ap-south-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
